# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '29th-iOS-SeminarPractice-week4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 5.4'

  # Pods for 29th-iOS-SeminarPractice-week4

end
